GET http://localhost:8882/hello
Accept: application/json

###

POST http://localhost:8882/hello/post
Content-Type: application/x-www-form-urlencoded

name=Test

###

GET http://localhost:8882/test/list
Accept: application/json

###

GET http://localhost:8882/test/animal
Accept: application/json


###